apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deploy
  labels:
    app: calculator-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-container
        image: gopallpatell/calculator:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  labels:
    app: calculator-app
spec:
  selector:
    app: calculator-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
